name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Cordova
        run: npm install -g cordova

      - name: Install project dependencies
        run: npm install

      - name: Add iOS platform
        run: cordova platform add ios

      - name: Build iOS
        run: cordova build ios

      - name: Upload iOS build
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: platforms/ios/build
